// D&D 5e Standard Weapon Properties and Definitions
export const WEAPON_DEFINITIONS = {
  dagger: { damage: '1d4', type: 'piercing', finesse: true, light: true, simple: true, thrown: '20/60' },
  dart: { damage: '1d4', type: 'piercing', finesse: true, ranged: true, simple: true, range: '20/60' },
  shortsword: { damage: '1d6', type: 'piercing', finesse: true, light: true, martial: true },
  scimitar: { damage: '1d6', type: 'slashing', finesse: true, light: true, martial: true },
  rapier: { damage: '1d8', type: 'piercing', finesse: true, martial: true },
  whip: { damage: '1d4', type: 'slashing', finesse: true, reach: true, martial: true },
  club: { damage: '1d4', type: 'bludgeoning', light: true, simple: true },
  greatclub: { damage: '1d8', type: 'bludgeoning', twoHanded: true, simple: true },
  mace: { damage: '1d6', type: 'bludgeoning', simple: true },
  quarterstaff: { damage: '1d6', versatile: '1d8', type: 'bludgeoning', simple: true },
  spear: { damage: '1d6', versatile: '1d8', type: 'piercing', simple: true, thrown: '20/60' },
  javelin: { damage: '1d6', type: 'piercing', simple: true, thrown: '30/120' },
  handaxe: { damage: '1d6', type: 'slashing', light: true, simple: true, thrown: '20/60' },
  battleaxe: { damage: '1d8', versatile: '1d10', type: 'slashing', martial: true },
  flail: { damage: '1d8', type: 'bludgeoning', martial: true },
  glaive: { damage: '1d10', type: 'slashing', reach: true, heavy: true, twoHanded: true, martial: true },
  greataxe: { damage: '1d12', type: 'slashing', heavy: true, twoHanded: true, martial: true },
  greatsword: { damage: '2d6', type: 'slashing', heavy: true, twoHanded: true, martial: true },
  halberd: { damage: '1d10', type: 'slashing', reach: true, heavy: true, twoHanded: true, martial: true },
  lance: { damage: '1d12', type: 'piercing', reach: true, martial: true },
  longsword: { damage: '1d8', versatile: '1d10', type: 'slashing', martial: true },
  maul: { damage: '2d6', type: 'bludgeoning', heavy: true, twoHanded: true, martial: true },
  morningstar: { damage: '1d8', type: 'piercing', martial: true },
  pike: { damage: '1d10', type: 'piercing', reach: true, heavy: true, twoHanded: true, martial: true },
  trident: { damage: '1d6', versatile: '1d8', type: 'piercing', simple: true, thrown: '20/60' },
  war_pick: { damage: '1d8', type: 'piercing', martial: true },
  warhammer: { damage: '1d8', versatile: '1d10', type: 'bludgeoning', martial: true },
  light_crossbow: { damage: '1d8', type: 'piercing', ranged: true, range: '80/320', twoHanded: true, simple: true },
  shortbow: { damage: '1d6', type: 'piercing', ranged: true, range: '80/320', twoHanded: true, simple: true },
  sling: { damage: '1d4', type: 'bludgeoning', ranged: true, range: '30/120', simple: true },
  blowgun: { damage: '1', type: 'piercing', ranged: true, range: '25/100', martial: true },
  hand_crossbow: { damage: '1d6', type: 'piercing', ranged: true, range: '30/120', light: true, martial: true },
  heavy_crossbow: { damage: '1d10', type: 'piercing', ranged: true, range: '100/400', heavy: true, twoHanded: true, martial: true },
  longbow: { damage: '1d8', type: 'piercing', ranged: true, range: '150/600', heavy: true, twoHanded: true, martial: true }
}
